[build]
  publish = "public"
  command = "cd functions && npm install && cd .. && hugo --gc --minify"
  functions = "functions/"

[context.production.environment]
  HUGO_VERSION = "0.59.1"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.59.1"
