[build]
  publish = "public"
  command = "cd functions && npm install && cd .. && hugo --gc --minify"
  functions = "functions/"

[context.production.environment]
  HUGO_VERSION = "v0.70.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "v0.70.0"

[dev]
  command = "hugo server --baseUrl=http://localhost:8888/ --appendPort=false"
